Repository swap-it-all/swap-it-an, pull requests merged in 2025-03, with the labels that each got.

#57 [FEAT] 쇼핑 세부화면 API 연결
  app/src/main/java/com/example/swapit/data/datasource/RemoteShoppingDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteShoppingDetailDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/ServiceModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/ShoppingProductResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/ShoppingProductsResultsResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/detail/ShoppingDetailDataResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/detail/ShoppingDetailImageResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/detail/ShoppingDetailUserResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ShoppingDetailService.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ShoppingService.kt
  app/src/main/java/com/example/swapit/data/mapper/Shopping.kt
  app/src/main/java/com/example/swapit/data/mapper/ShoppingDetail.kt
  app/src/main/java/com/example/swapit/data/model/ShoppingDetailData.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultShoppingDetailRepository.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultShoppingRepository.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/ShoppingProduct.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/ShoppingProductResults.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/detail/ShoppingDetailData.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/detail/ShoppingDetailImage.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/detail/ShoppingDetailUser.kt
  app/src/main/java/com/example/swapit/domain/repository/ShoppingDetailRepository.kt
  app/src/main/java/com/example/swapit/ui/chat/room/BottomChatBar.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/shopping/CategorySection.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingCard.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ProductContentSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ProductImageSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/model/CalculateTime.kt
Labels: FEAT

#59 [FEAT] 스왑 요청 연동 및 검색, 쇼핑 세부, 정렬 리펙토링
  app/src/main/java/com/example/swapit/MainActivity.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteMyProductSelectDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteShoppingDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteSwapRequestDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/local/model/bottomsheet/SortOption.kt
  app/src/main/java/com/example/swapit/data/datasource/local/model/search/PopularSearchTerm.kt
  app/src/main/java/com/example/swapit/data/datasource/local/model/search/RecentSearchTerm.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/ServiceModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/request/swap/SwapRequest.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/ShoppingProductsResultsResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ProductService.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ShoppingService.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/SwapService.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultMyProductSelectRepository.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultShoppingRepository.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultSwapRequestRepository.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/ShoppingProductResults.kt
  app/src/main/java/com/example/swapit/domain/repository/MyProductSelectRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/ShoppingRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/SwapRequestRepository.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/post/PostProductScreen.kt
  app/src/main/java/com/example/swapit/ui/search/PopularTermButtonField.kt
  app/src/main/java/com/example/swapit/ui/search/RecentTermButtonField.kt
  app/src/main/java/com/example/swapit/ui/search/SearchAppBar.kt
  app/src/main/java/com/example/swapit/ui/search/SearchField.kt
  app/src/main/java/com/example/swapit/ui/search/SearchScreen.kt
  app/src/main/java/com/example/swapit/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/SearchBarButton.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingSortBottomSheetContent.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/BottomButtonSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/DialogSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/MyProductSelectScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/MyProductSelectViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/MyProductSelectionScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/ProductListSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/SwapProductViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/TextSection.kt
  app/src/main/java/com/example/swapit/ui/swap/ReceivedSwapSection.kt
  app/src/main/java/com/example/swapit/ui/swap/SentSwapSection.kt
  app/src/main/java/com/example/swapit/ui/swap/SwapCard.kt
  app/src/main/res/values/strings.xml
Labels: FEAT

#61 [FEAT] 사용자 정보 수정 페이지 네트워크 연결
  app/src/main/java/com/example/swapit/data/datasource/RemoteUserDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/request/user/UserProfileRequest.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/user/UserResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/UserService.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultUserRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/UserRepository.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoScreen.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoViewModel.kt
  app/src/main/java/com/example/swapit/ui/user/profile/ProfileEditScreen.kt
  app/src/main/java/com/example/swapit/ui/user/profile/ProfileImage.kt
  app/src/main/java/com/example/swapit/ui/user/profile/ProfileNameTextField.kt
Labels: FEAT

#63 [REFACTOR] 물건 DTO 및 서비스 파일명 수정
  app/src/main/java/com/example/swapit/MainActivity.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteMyProductSelectDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteProductDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteShoppingDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteShoppingDetailDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/RemoteSwapDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/ServiceModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/product/ProductResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/product/ProductResultResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/product/detail/ProductDetailImageResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/product/detail/ProductDetailResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/product/detail/ProductDetailUserResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/ShoppingProductsResultsResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/detail/ShoppingDetailImageResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ProductService.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ShoppingDetailService.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ShoppingService.kt
  app/src/main/java/com/example/swapit/data/mapper/Product.kt
  app/src/main/java/com/example/swapit/data/mapper/Shopping.kt
  app/src/main/java/com/example/swapit/data/mapper/ShoppingDetail.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultMyProductSelectRepository.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultProductRepository.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultShoppingDetailRepository.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultShoppingRepository.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultSwapRepository.kt
  app/src/main/java/com/example/swapit/domain/model/product/Product.kt
  app/src/main/java/com/example/swapit/domain/model/product/ProductResults.kt
  app/src/main/java/com/example/swapit/domain/model/product/detail/ProductDetail.kt
  app/src/main/java/com/example/swapit/domain/model/product/detail/ProductDetailImage.kt
  app/src/main/java/com/example/swapit/domain/model/product/detail/ProductDetailUser.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/ShoppingProductResults.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/detail/ShoppingDetailImage.kt
  app/src/main/java/com/example/swapit/domain/repository/MyProductSelectRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/ProductRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/ShoppingDetailRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/ShoppingRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/SwapRepository.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/search/SearchScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/SearchBarButton.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingCard.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/BottomButtonSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ProductContentSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ProductImageSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/MyProductSelectScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/MyProductSelectViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/SwapProductViewModel.kt
Labels: REFACTOR

#67 [FEAT] [FEAT] 채팅 API 연결
  app/build.gradle.kts
  app/src/main/java/com/example/swapit/data/datasource/RemoteChatDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/local/model/chat/ChatType.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/RetrofitModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/ServiceModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/request/chat/ChatReadRequest.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/request/chat/ChatRequest.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/request/chat/GoodsIdRequest.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/request/chat/TradesIdRequest.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/chat/ChatResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/chat/ChatRoomInfoResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/chat/ChatRoomResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ChatService.kt
  app/src/main/java/com/example/swapit/data/mapper/Chat.kt
  app/src/main/java/com/example/swapit/data/model/AlertCardData.kt
  app/src/main/java/com/example/swapit/data/model/CardData.kt
  app/src/main/java/com/example/swapit/data/model/ChatData.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultChatRepository.kt
  app/src/main/java/com/example/swapit/domain/model/chat/Chat.kt
  app/src/main/java/com/example/swapit/domain/model/chat/ChatRoom.kt
  app/src/main/java/com/example/swapit/domain/model/chat/ChatRoomInfo.kt
  app/src/main/java/com/example/swapit/domain/repository/ChatRepository.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatCard.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatListScreen.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatViewModel.kt
  app/src/main/java/com/example/swapit/ui/chat/NoChatIconSection.kt
  app/src/main/java/com/example/swapit/ui/chat/room/BottomChatBar.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatBubble.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomAppBar.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomContent.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomProduct.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomScreen.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomTradeButtonBar.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/AfterSwapBottomButtonSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/BeforeSwapBottomButtonSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/CompleteSwapBottomButtonSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ReceivedSwapBottomButtonSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailScreen.kt
  gradle/libs.versions.toml
Labels: FEAT

#76 [FEAT] 로그아웃
  app/src/main/java/com/example/swapit/ui/navigation/NavItem.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/post/PostAppBar.kt
  app/src/main/java/com/example/swapit/ui/post/PostProductScreen.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoAppBar.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoScreen.kt
  app/src/main/java/com/example/swapit/ui/user/setting/SettingScreen.kt
Labels: FEAT

#77 Feat/withdraw
  app/src/main/java/com/example/swapit/data/datasource/remote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/example/swapit/ui/alert/AlertAppBar.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatViewModel.kt
  app/src/main/java/com/example/swapit/ui/chat/room/BottomChatBar.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatBubble.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomScreen.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavItem.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoViewModel.kt
  app/src/main/java/com/example/swapit/ui/user/setting/SettingScreen.kt
  app/src/main/java/com/example/swapit/ui/user/setting/withdraw/WithdrawAppBar.kt
  app/src/main/java/com/example/swapit/ui/user/setting/withdraw/WithdrawDropdownMenu.kt
  app/src/main/java/com/example/swapit/ui/user/setting/withdraw/WithdrawScreen.kt
Labels: UI
