Repository swap-it-all/swap-it-an, pull requests merged in 2025-02, with the labels that each got.

#11 [UI] 로그인 화면 구현
  .github/pull_request_template.md
  app/build.gradle.kts
  app/src/androidTest/java/com/example/swap_it/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/swap_it/MainActivity.kt
  app/src/main/java/com/example/swap_it/ui/auth/AuthActivity.kt
  app/src/main/java/com/example/swap_it/ui/component/Buttons.kt
  app/src/main/java/com/example/swap_it/ui/theme/Shape.kt
  app/src/main/java/com/example/swap_it/ui/theme/Theme.kt
  app/src/main/java/com/example/swap_it/ui/theme/Type.kt
  app/src/main/res/drawable/ic_logo.xml
  app/src/test/java/com/example/swap_it/ExampleUnitTest.kt
Labels: UI

#7 [UI] 프로덕트 리스트 스크린 및 메뉴 스크린 작성
  app/build.gradle.kts
  app/src/main/java/com/example/swap_it/MainActivity.kt
  app/src/main/java/com/example/swap_it/ui/add_item/AddItemScreen.kt
  app/src/main/java/com/example/swap_it/ui/chat_list/ChatListScreen.kt
  app/src/main/java/com/example/swap_it/ui/component/Buttons.kt
  app/src/main/java/com/example/swap_it/ui/component/ProductCards.kt
  app/src/main/java/com/example/swap_it/ui/menu/MenuScreen.kt
  app/src/main/java/com/example/swap_it/ui/product_list/ProductListScreen.kt
  app/src/main/java/com/example/swap_it/ui/shopping_list/ShoppingListScreen.kt
  app/src/main/java/com/example/swap_it/ui/user_info/UserInfoScreen.kt
  app/src/main/res/drawable/ic_logo.xml
  gradle/libs.versions.toml
Labels: UI

#19 [UI,FEAT] 물건 등록 화면 구현 및 텍스트필드 검증
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/swap_it/data/datasource/local/model/post/CategoryOption.kt
  app/src/main/java/com/example/swap_it/data/datasource/local/model/post/QualityOption.kt
  app/src/main/java/com/example/swap_it/domain/model/post/Description.kt
  app/src/main/java/com/example/swap_it/domain/model/post/Location.kt
  app/src/main/java/com/example/swap_it/domain/model/post/Name.kt
  app/src/main/java/com/example/swap_it/domain/model/post/Price.kt
  app/src/main/java/com/example/swap_it/domain/model/post/ValidationResult.kt
  app/src/main/java/com/example/swap_it/ui/component/Buttons.kt
  app/src/main/java/com/example/swap_it/ui/component/TextFields.kt
  app/src/main/java/com/example/swap_it/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductCategory.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductQuality.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductScreen.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductViewModel.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductDescriptionTextField.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductImagePicker.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductNameTextField.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductPriceTextField.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductSwapLocationTextField.kt
  app/src/main/res/values/strings.xml
Labels: UI, FEAT

#26 [FEAT] Github Action 이용하여 CI 작업
  .github/workflows/android.yml
Labels: FEAT

#21 [UI] - 거래화면 구현 및 리펙토링
  app/build.gradle.kts
  app/src/main/java/com/example/swap_it/data/datasource/local/model/bottomsheet/SortOption.kt
  app/src/main/java/com/example/swap_it/data/datasource/local/model/search/PopularSearchTerm.kt
  app/src/main/java/com/example/swap_it/data/datasource/local/model/search/RecentSearchTerm.kt
  app/src/main/java/com/example/swap_it/data/model/CardData.kt
  app/src/main/java/com/example/swap_it/ui/add_item/AddItemScreen.kt
  app/src/main/java/com/example/swap_it/ui/alert/AlertCard.kt
  app/src/main/java/com/example/swap_it/ui/alert/AlertScreen.kt
  app/src/main/java/com/example/swap_it/ui/chat/ChatListScreen.kt
  app/src/main/java/com/example/swap_it/ui/component/AppBar.kt
  app/src/main/java/com/example/swap_it/ui/component/BottomNavigationBar.kt
  app/src/main/java/com/example/swap_it/ui/component/Buttons.kt
  app/src/main/java/com/example/swap_it/ui/component/Cards.kt
  app/src/main/java/com/example/swap_it/ui/navigation/BottomNavItem.kt
  app/src/main/java/com/example/swap_it/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swap_it/ui/search/PopularTermButtonField.kt
  app/src/main/java/com/example/swap_it/ui/search/RecentTermButtonField.kt
  app/src/main/java/com/example/swap_it/ui/search/SearchField.kt
  app/src/main/java/com/example/swap_it/ui/search/SearchScreen.kt
  app/src/main/java/com/example/swap_it/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/swap_it/ui/shopping/Alert.kt
  app/src/main/java/com/example/swap_it/ui/shopping/CategorySection.kt
  app/src/main/java/com/example/swap_it/ui/shopping/ModalBottomSheetContent.kt
  app/src/main/java/com/example/swap_it/ui/shopping/SearchBarButton.kt
  app/src/main/java/com/example/swap_it/ui/shopping/SearchScreen.kt
  app/src/main/java/com/example/swap_it/ui/shopping/Shopping.kt
  app/src/main/java/com/example/swap_it/ui/shopping/ShoppingCard.kt
  app/src/main/java/com/example/swap_it/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swap_it/ui/swap/RequestSwapSection.kt
  app/src/main/java/com/example/swap_it/ui/swap/RequestedSwapSection.kt
  app/src/main/java/com/example/swap_it/ui/swap/ShoppingListScreen.kt
  app/src/main/java/com/example/swap_it/ui/swap/SwapCard.kt
  app/src/main/java/com/example/swap_it/ui/swap/SwapScreen.kt
  app/src/main/java/com/example/swap_it/ui/theme/Paddings.kt
  app/src/main/java/com/example/swap_it/ui/user/UserInfoScreen.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: UI

#23 [UI] 쇼핑 상세 화면 구현
  app/src/main/java/com/example/swap_it/data/model/CardData.kt
  app/src/main/java/com/example/swap_it/data/model/ShoppingDetailData.kt
  app/src/main/java/com/example/swap_it/ui/alert/AlertScreen.kt
  app/src/main/java/com/example/swap_it/ui/component/BottomNavigationBar.kt
  app/src/main/java/com/example/swap_it/ui/component/Buttons.kt
  app/src/main/java/com/example/swap_it/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swap_it/ui/search/SearchScreen.kt
  app/src/main/java/com/example/swap_it/ui/shopping/CategorySection.kt
  app/src/main/java/com/example/swap_it/ui/shopping/ModalBottomSheetContent.kt
  app/src/main/java/com/example/swap_it/ui/shopping/SearchBarButton.kt
  app/src/main/java/com/example/swap_it/ui/shopping/ShoppingCard.kt
  app/src/main/java/com/example/swap_it/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swap_it/ui/shopping/detail/BottomButtonSection.kt
  app/src/main/java/com/example/swap_it/ui/shopping/detail/ProductContentSection.kt
  app/src/main/java/com/example/swap_it/ui/shopping/detail/ProductImageSection.kt
  app/src/main/java/com/example/swap_it/ui/shopping/detail/ShoppingDetailScreen.kt
  app/src/main/java/com/example/swap_it/ui/swap/SwapCard.kt
  app/src/main/res/drawable/ic_filled_star.xml
Labels: UI

#24 [FEAT] 물건 등록 시 필요한 상태 관리
  app/src/main/java/com/example/swap_it/MainActivity.kt
  app/src/main/java/com/example/swap_it/data/datasource/local/model/post/CategoryOption.kt
  app/src/main/java/com/example/swap_it/domain/model/post/Location.kt
  app/src/main/java/com/example/swap_it/domain/model/post/Name.kt
  app/src/main/java/com/example/swap_it/domain/model/post/PostState.kt
  app/src/main/java/com/example/swap_it/ui/add_item/AddItemScreen.kt
  app/src/main/java/com/example/swap_it/ui/chat/ChatListScreen.kt
  app/src/main/java/com/example/swap_it/ui/component/AlertDialog.kt
  app/src/main/java/com/example/swap_it/ui/component/AppBar.kt
  app/src/main/java/com/example/swap_it/ui/component/BottomNavigationBar.kt
  app/src/main/java/com/example/swap_it/ui/component/Buttons.kt
  app/src/main/java/com/example/swap_it/ui/component/Cards.kt
  app/src/main/java/com/example/swap_it/ui/component/TextFields.kt
  app/src/main/java/com/example/swap_it/ui/navigation/BottomNavItem.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductCategory.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductQuality.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductScreen.kt
  app/src/main/java/com/example/swap_it/ui/post/PostProductViewModel.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductDescriptionTextField.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductImagePicker.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductNameTextField.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductPriceTextField.kt
  app/src/main/java/com/example/swap_it/ui/post/component/PostProductSwapLocationTextField.kt
  app/src/main/java/com/example/swap_it/ui/post/model/AlertDialogState.kt
  app/src/main/java/com/example/swap_it/ui/shopping/Alert.kt
  app/src/main/java/com/example/swap_it/ui/shopping/SearchBarButton.kt
  app/src/main/java/com/example/swap_it/ui/shopping/SearchScreen.kt
  app/src/main/java/com/example/swap_it/ui/shopping/Shopping.kt
  app/src/main/java/com/example/swap_it/ui/swap/ShoppingListScreen.kt
  app/src/main/java/com/example/swap_it/ui/user/UserInfoScreen.kt
Labels: FEAT

#29 [CONFIG] Coil 네트워크 이미지 의존성 추가
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: CONFIG

#35 [UI] 상세화면 -> 스왑하기 -> 내 물건 선택 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/example/swapit/ui/alert/AlertCard.kt
  app/src/main/java/com/example/swapit/ui/component/AlertDialog.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/search/SearchField.kt
  app/src/main/java/com/example/swapit/ui/shopping/CategorySection.kt
  app/src/main/java/com/example/swapit/ui/shopping/ModalBottomSheetContent.kt
  app/src/main/java/com/example/swapit/ui/shopping/SearchBarButton.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingCard.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/BottomButtonSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ProductContentSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ProductImageSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/ShoppingDetailScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/BackButtonAndTextSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/DialogSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/MyProductSelectionScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/ProductListSection.kt
  app/src/main/java/com/example/swapit/ui/swap/ReceivedSwapSection.kt
  app/src/main/java/com/example/swapit/ui/swap/SentSwapSection.kt
  app/src/main/java/com/example/swapit/ui/swap/SwapCard.kt
  app/src/main/java/com/example/swapit/ui/swap/SwapScreen.kt
  app/src/main/res/values/strings.xml
Labels: UI

#40 [FEAT] API 호출 시 인터셉터 추가
  app/src/main/java/com/example/swapit/SwapItApplication.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/RetrofitModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/interceptor/AuthAuthenticator.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/interceptor/LoggingInterceptor.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultLoginRepository.kt
Labels: FEAT

#41 [UI] 채팅 리스트 스크린 구현
  app/src/main/java/com/example/swapit/data/model/CardData.kt
  app/src/main/java/com/example/swapit/ui/alert/AlertScreen.kt
  app/src/main/java/com/example/swapit/ui/alert/NoAlertIconSection.kt
  app/src/main/java/com/example/swapit/ui/auth/LoginScreen.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatCard.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatListScreen.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatScreen.kt
  app/src/main/java/com/example/swapit/ui/chat/NoChatIconSection.kt
  app/src/main/java/com/example/swapit/ui/component/AppBar.kt
  app/src/main/java/com/example/swapit/ui/component/BottomNavigationBar.kt
  app/src/main/java/com/example/swapit/ui/navigation/BottomNavItem.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavItem.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/shopping/SearchBarButton.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/BottomButtonSection.kt
  app/src/main/res/drawable/ic_no_alert.xml
  app/src/main/res/drawable/ic_no_chat.xml
Labels: UI

#42 [FEAT] 물건 등록 API 연동 및 토큰 관리
  app/src/main/java/com/example/swapit/data/datasource/RemoteProductDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/RetrofitModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/ServiceModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/request/product/ProductRequest.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/interceptor/AuthAuthenticator.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ProductService.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultProductRepository.kt
  app/src/main/java/com/example/swapit/domain/repository/ProductRepository.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/post/PostProductScreen.kt
  app/src/main/java/com/example/swapit/ui/post/PostProductViewModel.kt
Labels: FEAT

#45 [UI] 마이페이지 화면 구현
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/user/ProfileCard.kt
  app/src/main/java/com/example/swapit/ui/user/ProfileItem.kt
  app/src/main/java/com/example/swapit/ui/user/ProfileSwapCard.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoScreen.kt
  app/src/main/res/drawable/ic_pencil.xml
Labels: UI

#47 [UI] 마이페이지 프로필 수정 화면 구현
  app/src/main/java/com/example/swapit/ui/navigation/NavItem.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/user/ProfileCard.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoScreen.kt
  app/src/main/java/com/example/swapit/ui/user/profile/ProfileEditAppBar.kt
  app/src/main/java/com/example/swapit/ui/user/profile/ProfileEditScreen.kt
  app/src/main/java/com/example/swapit/ui/user/profile/ProfileImage.kt
  app/src/main/java/com/example/swapit/ui/user/profile/ProfileNameTextField.kt
Labels: UI

#49 [UI] 채팅방 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/swapit/data/model/ChatData.kt
  app/src/main/java/com/example/swapit/ui/alert/AlertAppBar.kt
  app/src/main/java/com/example/swapit/ui/alert/AlertScreen.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatCard.kt
  app/src/main/java/com/example/swapit/ui/chat/ChatScreen.kt
  app/src/main/java/com/example/swapit/ui/chat/room/BottomChatBar.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatBubble.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomAppBar.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomContent.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomProduct.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomScreen.kt
  app/src/main/java/com/example/swapit/ui/component/AppBar.kt
  app/src/main/java/com/example/swapit/ui/component/Buttons.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavItem.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/search/SearchAppBar.kt
  app/src/main/java/com/example/swapit/ui/search/SearchField.kt
  app/src/main/java/com/example/swapit/ui/search/SearchScreen.kt
  app/src/main/res/values/strings.xml
Labels: UI

#51 [FEAT,UI] 앱 스플래시 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/example/swapit/ui/navigation/NavItem.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/post/PostProductScreen.kt
  app/src/main/java/com/example/swapit/ui/splash/SplashScreen.kt
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: UI, FEAT

#53 [FEAT] 물건 리스트 화면 구현
  app/src/main/java/com/example/swapit/data/datasource/RemoteShoppingDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/RetrofitModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/ServiceModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/ShoppingCardProduct.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/shopping/ShoppingCardProductsResults.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/ShoppingService.kt
  app/src/main/java/com/example/swapit/data/model/ChatData.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultShoppingRepository.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/ShoppingProduct.kt
  app/src/main/java/com/example/swapit/domain/model/shopping/ShoppingProductResults.kt
  app/src/main/java/com/example/swapit/domain/repository/ShoppingRepository.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomContent.kt
  app/src/main/java/com/example/swapit/ui/chat/room/ChatRoomScreen.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingCard.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/ShoppingViewModel.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/MyProductSelectionScreen.kt
  app/src/main/java/com/example/swapit/ui/shopping/detail/select/ProductListSection.kt
  app/src/main/java/com/example/swapit/ui/shopping/model/CalculateTime.kt
Labels: FEAT

#55 [FEAT] 사용자 정보 페이지 네트워크 연결
  app/src/main/java/com/example/swapit/data/datasource/RemoteUserDataSource.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/ServiceModule.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/user/ReviewResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/dto/response/user/UserResponse.kt
  app/src/main/java/com/example/swapit/data/datasource/remote/service/UserService.kt
  app/src/main/java/com/example/swapit/data/mapper/User.kt
  app/src/main/java/com/example/swapit/data/repository/DefaultUserRepository.kt
  app/src/main/java/com/example/swapit/domain/model/user/Review.kt
  app/src/main/java/com/example/swapit/domain/model/user/UserInfo.kt
  app/src/main/java/com/example/swapit/domain/model/user/UserSwapStats.kt
  app/src/main/java/com/example/swapit/domain/repository/UserRepository.kt
  app/src/main/java/com/example/swapit/ui/navigation/NavigationModule.kt
  app/src/main/java/com/example/swapit/ui/splash/SplashScreen.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoScreen.kt
  app/src/main/java/com/example/swapit/ui/user/UserInfoViewModel.kt
  app/src/main/java/com/example/swapit/ui/user/UserProfileCard.kt
  app/src/main/java/com/example/swapit/ui/user/UserProfileItem.kt
  app/src/main/java/com/example/swapit/ui/user/UserSwapCard.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
Labels: FEAT
